/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package robotlogger;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author msto
 */
public class StringStream extends JFrame implements PacketReceiver.StringPacketClient {

    private List<String> queue;
    private volatile boolean ignore;
    private volatile int maxlen;

    /**
     * Creates new form StringStream
     */
    public StringStream() {
        initComponents();

        queue = null;
        jToggleButton1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                ignore = jToggleButton1.isSelected();
            }
        });

        Graph.configJSpinner(spinMaxLines, new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                maxlen = (Integer) spinMaxLines.getValue();
                if (jTextArea1.getLineCount() > maxlen) {
                    jTextArea1.setText("");
                }
            }
        });

        ignore = false;
        maxlen = (Integer) spinMaxLines.getValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spinMaxLines = new javax.swing.JSpinner();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jLabel1.setText("Max Lines");
        jPanel2.add(jLabel1);

        spinMaxLines.setModel(new javax.swing.SpinnerNumberModel(2000, 500, 100000, 500));
        jPanel2.add(spinMaxLines);

        jToggleButton1.setText("Ignore");
        jPanel2.add(jToggleButton1);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JSpinner spinMaxLines;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setQueue(List<String> s) {
        queue = s;
    }

    @Override
    public void newPackets(int k) {
        if (ignore) {
            return;
        }
        final String next = queue.get(queue.size() - 1);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jTextArea1.append(next + "\n");
                if (jTextArea1.getLineCount() > maxlen) {
                    jTextArea1.setText("");
                }
            }
        });
    }
}
